//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudService.Database
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class Routes
    {
        public Routes()
        {
            this.RoutePoints = new HashSet<RoutePoints>();
        }
    
        [DataMember]
        public int idRoutes { get; set; }
        [DataMember]
        public System.DateTime ExerciseStart { get; set; }
        [DataMember]
        public System.DateTime ExerciseEnd { get; set; }
        [DataMember]
        public string Users_Email { get; set; }
    
        [DataMember]
        public virtual ICollection<RoutePoints> RoutePoints { get; set; }
        [DataMember]
        public virtual Users Users { get; set; }
    }
}
