//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace Domain.CloudService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://schemas.datacontract.org/2004/07/CloudService.Database", IsReference=true)]
    public partial class Users : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EmailField;
        
        private System.Collections.ObjectModel.ObservableCollection<Domain.CloudService.Exercises> ExercisesField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Domain.CloudService.Exercises> Exercises {
            get {
                return this.ExercisesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExercisesField, value) != true)) {
                    this.ExercisesField = value;
                    this.RaisePropertyChanged("Exercises");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Exercises", Namespace="http://schemas.datacontract.org/2004/07/CloudService.Database", IsReference=true)]
    public partial class Exercises : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime ExerciseEndField;
        
        private System.DateTime ExerciseStartField;
        
        private System.Collections.ObjectModel.ObservableCollection<Domain.CloudService.RoutePoints> RoutePointsField;
        
        private Domain.CloudService.Users UsersField;
        
        private string Users_EmailField;
        
        private int idExercisesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExerciseEnd {
            get {
                return this.ExerciseEndField;
            }
            set {
                if ((this.ExerciseEndField.Equals(value) != true)) {
                    this.ExerciseEndField = value;
                    this.RaisePropertyChanged("ExerciseEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExerciseStart {
            get {
                return this.ExerciseStartField;
            }
            set {
                if ((this.ExerciseStartField.Equals(value) != true)) {
                    this.ExerciseStartField = value;
                    this.RaisePropertyChanged("ExerciseStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Domain.CloudService.RoutePoints> RoutePoints {
            get {
                return this.RoutePointsField;
            }
            set {
                if ((object.ReferenceEquals(this.RoutePointsField, value) != true)) {
                    this.RoutePointsField = value;
                    this.RaisePropertyChanged("RoutePoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Domain.CloudService.Users Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Users_Email {
            get {
                return this.Users_EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.Users_EmailField, value) != true)) {
                    this.Users_EmailField = value;
                    this.RaisePropertyChanged("Users_Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idExercises {
            get {
                return this.idExercisesField;
            }
            set {
                if ((this.idExercisesField.Equals(value) != true)) {
                    this.idExercisesField = value;
                    this.RaisePropertyChanged("idExercises");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoutePoints", Namespace="http://schemas.datacontract.org/2004/07/CloudService.Database", IsReference=true)]
    public partial class RoutePoints : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Domain.CloudService.Exercises ExercisesField;
        
        private int Exercises_idRouteField;
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        private System.DateTime TimeField;
        
        private int idRoutePointsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Domain.CloudService.Exercises Exercises {
            get {
                return this.ExercisesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExercisesField, value) != true)) {
                    this.ExercisesField = value;
                    this.RaisePropertyChanged("Exercises");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Exercises_idRoute {
            get {
                return this.Exercises_idRouteField;
            }
            set {
                if ((this.Exercises_idRouteField.Equals(value) != true)) {
                    this.Exercises_idRouteField = value;
                    this.RaisePropertyChanged("Exercises_idRoute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idRoutePoints {
            get {
                return this.idRoutePointsField;
            }
            set {
                if ((this.idRoutePointsField.Equals(value) != true)) {
                    this.idRoutePointsField = value;
                    this.RaisePropertyChanged("idRoutePoints");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CloudService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/Login", ReplyAction="http://tempuri.org/IService/LoginResponse")]
        System.IAsyncResult BeginLogin(Domain.CloudService.Users user, System.AsyncCallback callback, object asyncState);
        
        string EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/Register", ReplyAction="http://tempuri.org/IService/RegisterResponse")]
        System.IAsyncResult BeginRegister(Domain.CloudService.Users user, System.AsyncCallback callback, object asyncState);
        
        string EndRegister(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/SaveExercise", ReplyAction="http://tempuri.org/IService/SaveExerciseResponse")]
        System.IAsyncResult BeginSaveExercise(Domain.CloudService.Users user, Domain.CloudService.Exercises exercise, System.AsyncCallback callback, object asyncState);
        
        string EndSaveExercise(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetExercisesLight", ReplyAction="http://tempuri.org/IService/GetExercisesLightResponse")]
        System.IAsyncResult BeginGetExercisesLight(Domain.CloudService.Users user, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Domain.CloudService.Exercises> EndGetExercisesLight(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetFullExercise", ReplyAction="http://tempuri.org/IService/GetFullExerciseResponse")]
        System.IAsyncResult BeginGetFullExercise(Domain.CloudService.Users user, int exerciseID, System.AsyncCallback callback, object asyncState);
        
        Domain.CloudService.Exercises EndGetFullExercise(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Domain.CloudService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveExerciseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveExerciseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetExercisesLightCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetExercisesLightCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Domain.CloudService.Exercises> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Domain.CloudService.Exercises>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFullExerciseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFullExerciseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Domain.CloudService.Exercises Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Domain.CloudService.Exercises)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Domain.CloudService.IService>, Domain.CloudService.IService {
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginRegisterDelegate;
        
        private EndOperationDelegate onEndRegisterDelegate;
        
        private System.Threading.SendOrPostCallback onRegisterCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveExerciseDelegate;
        
        private EndOperationDelegate onEndSaveExerciseDelegate;
        
        private System.Threading.SendOrPostCallback onSaveExerciseCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetExercisesLightDelegate;
        
        private EndOperationDelegate onEndGetExercisesLightDelegate;
        
        private System.Threading.SendOrPostCallback onGetExercisesLightCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFullExerciseDelegate;
        
        private EndOperationDelegate onEndGetFullExerciseDelegate;
        
        private System.Threading.SendOrPostCallback onGetFullExerciseCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<RegisterCompletedEventArgs> RegisterCompleted;
        
        public event System.EventHandler<SaveExerciseCompletedEventArgs> SaveExerciseCompleted;
        
        public event System.EventHandler<GetExercisesLightCompletedEventArgs> GetExercisesLightCompleted;
        
        public event System.EventHandler<GetFullExerciseCompletedEventArgs> GetFullExerciseCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Domain.CloudService.IService.BeginLogin(Domain.CloudService.Users user, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(user, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string Domain.CloudService.IService.EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Domain.CloudService.Users user = ((Domain.CloudService.Users)(inValues[0]));
            return ((Domain.CloudService.IService)(this)).BeginLogin(user, callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            string retVal = ((Domain.CloudService.IService)(this)).EndLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync(Domain.CloudService.Users user) {
            this.LoginAsync(user, null);
        }
        
        public void LoginAsync(Domain.CloudService.Users user, object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        user}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Domain.CloudService.IService.BeginRegister(Domain.CloudService.Users user, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegister(user, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string Domain.CloudService.IService.EndRegister(System.IAsyncResult result) {
            return base.Channel.EndRegister(result);
        }
        
        private System.IAsyncResult OnBeginRegister(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Domain.CloudService.Users user = ((Domain.CloudService.Users)(inValues[0]));
            return ((Domain.CloudService.IService)(this)).BeginRegister(user, callback, asyncState);
        }
        
        private object[] OnEndRegister(System.IAsyncResult result) {
            string retVal = ((Domain.CloudService.IService)(this)).EndRegister(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRegisterCompleted(object state) {
            if ((this.RegisterCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegisterCompleted(this, new RegisterCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegisterAsync(Domain.CloudService.Users user) {
            this.RegisterAsync(user, null);
        }
        
        public void RegisterAsync(Domain.CloudService.Users user, object userState) {
            if ((this.onBeginRegisterDelegate == null)) {
                this.onBeginRegisterDelegate = new BeginOperationDelegate(this.OnBeginRegister);
            }
            if ((this.onEndRegisterDelegate == null)) {
                this.onEndRegisterDelegate = new EndOperationDelegate(this.OnEndRegister);
            }
            if ((this.onRegisterCompletedDelegate == null)) {
                this.onRegisterCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegisterCompleted);
            }
            base.InvokeAsync(this.onBeginRegisterDelegate, new object[] {
                        user}, this.onEndRegisterDelegate, this.onRegisterCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Domain.CloudService.IService.BeginSaveExercise(Domain.CloudService.Users user, Domain.CloudService.Exercises exercise, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveExercise(user, exercise, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string Domain.CloudService.IService.EndSaveExercise(System.IAsyncResult result) {
            return base.Channel.EndSaveExercise(result);
        }
        
        private System.IAsyncResult OnBeginSaveExercise(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Domain.CloudService.Users user = ((Domain.CloudService.Users)(inValues[0]));
            Domain.CloudService.Exercises exercise = ((Domain.CloudService.Exercises)(inValues[1]));
            return ((Domain.CloudService.IService)(this)).BeginSaveExercise(user, exercise, callback, asyncState);
        }
        
        private object[] OnEndSaveExercise(System.IAsyncResult result) {
            string retVal = ((Domain.CloudService.IService)(this)).EndSaveExercise(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveExerciseCompleted(object state) {
            if ((this.SaveExerciseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveExerciseCompleted(this, new SaveExerciseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveExerciseAsync(Domain.CloudService.Users user, Domain.CloudService.Exercises exercise) {
            this.SaveExerciseAsync(user, exercise, null);
        }
        
        public void SaveExerciseAsync(Domain.CloudService.Users user, Domain.CloudService.Exercises exercise, object userState) {
            if ((this.onBeginSaveExerciseDelegate == null)) {
                this.onBeginSaveExerciseDelegate = new BeginOperationDelegate(this.OnBeginSaveExercise);
            }
            if ((this.onEndSaveExerciseDelegate == null)) {
                this.onEndSaveExerciseDelegate = new EndOperationDelegate(this.OnEndSaveExercise);
            }
            if ((this.onSaveExerciseCompletedDelegate == null)) {
                this.onSaveExerciseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveExerciseCompleted);
            }
            base.InvokeAsync(this.onBeginSaveExerciseDelegate, new object[] {
                        user,
                        exercise}, this.onEndSaveExerciseDelegate, this.onSaveExerciseCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Domain.CloudService.IService.BeginGetExercisesLight(Domain.CloudService.Users user, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetExercisesLight(user, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Domain.CloudService.Exercises> Domain.CloudService.IService.EndGetExercisesLight(System.IAsyncResult result) {
            return base.Channel.EndGetExercisesLight(result);
        }
        
        private System.IAsyncResult OnBeginGetExercisesLight(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Domain.CloudService.Users user = ((Domain.CloudService.Users)(inValues[0]));
            return ((Domain.CloudService.IService)(this)).BeginGetExercisesLight(user, callback, asyncState);
        }
        
        private object[] OnEndGetExercisesLight(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Domain.CloudService.Exercises> retVal = ((Domain.CloudService.IService)(this)).EndGetExercisesLight(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetExercisesLightCompleted(object state) {
            if ((this.GetExercisesLightCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetExercisesLightCompleted(this, new GetExercisesLightCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetExercisesLightAsync(Domain.CloudService.Users user) {
            this.GetExercisesLightAsync(user, null);
        }
        
        public void GetExercisesLightAsync(Domain.CloudService.Users user, object userState) {
            if ((this.onBeginGetExercisesLightDelegate == null)) {
                this.onBeginGetExercisesLightDelegate = new BeginOperationDelegate(this.OnBeginGetExercisesLight);
            }
            if ((this.onEndGetExercisesLightDelegate == null)) {
                this.onEndGetExercisesLightDelegate = new EndOperationDelegate(this.OnEndGetExercisesLight);
            }
            if ((this.onGetExercisesLightCompletedDelegate == null)) {
                this.onGetExercisesLightCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetExercisesLightCompleted);
            }
            base.InvokeAsync(this.onBeginGetExercisesLightDelegate, new object[] {
                        user}, this.onEndGetExercisesLightDelegate, this.onGetExercisesLightCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Domain.CloudService.IService.BeginGetFullExercise(Domain.CloudService.Users user, int exerciseID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFullExercise(user, exerciseID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Domain.CloudService.Exercises Domain.CloudService.IService.EndGetFullExercise(System.IAsyncResult result) {
            return base.Channel.EndGetFullExercise(result);
        }
        
        private System.IAsyncResult OnBeginGetFullExercise(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Domain.CloudService.Users user = ((Domain.CloudService.Users)(inValues[0]));
            int exerciseID = ((int)(inValues[1]));
            return ((Domain.CloudService.IService)(this)).BeginGetFullExercise(user, exerciseID, callback, asyncState);
        }
        
        private object[] OnEndGetFullExercise(System.IAsyncResult result) {
            Domain.CloudService.Exercises retVal = ((Domain.CloudService.IService)(this)).EndGetFullExercise(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFullExerciseCompleted(object state) {
            if ((this.GetFullExerciseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFullExerciseCompleted(this, new GetFullExerciseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFullExerciseAsync(Domain.CloudService.Users user, int exerciseID) {
            this.GetFullExerciseAsync(user, exerciseID, null);
        }
        
        public void GetFullExerciseAsync(Domain.CloudService.Users user, int exerciseID, object userState) {
            if ((this.onBeginGetFullExerciseDelegate == null)) {
                this.onBeginGetFullExerciseDelegate = new BeginOperationDelegate(this.OnBeginGetFullExercise);
            }
            if ((this.onEndGetFullExerciseDelegate == null)) {
                this.onEndGetFullExerciseDelegate = new EndOperationDelegate(this.OnEndGetFullExercise);
            }
            if ((this.onGetFullExerciseCompletedDelegate == null)) {
                this.onGetFullExerciseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFullExerciseCompleted);
            }
            base.InvokeAsync(this.onBeginGetFullExerciseDelegate, new object[] {
                        user,
                        exerciseID}, this.onEndGetFullExerciseDelegate, this.onGetFullExerciseCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Domain.CloudService.IService CreateChannel() {
            return new ServiceClientChannel(this);
        }
        
        private class ServiceClientChannel : ChannelBase<Domain.CloudService.IService>, Domain.CloudService.IService {
            
            public ServiceClientChannel(System.ServiceModel.ClientBase<Domain.CloudService.IService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginLogin(Domain.CloudService.Users user, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = user;
                System.IAsyncResult _result = base.BeginInvoke("Login", _args, callback, asyncState);
                return _result;
            }
            
            public string EndLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("Login", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRegister(Domain.CloudService.Users user, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = user;
                System.IAsyncResult _result = base.BeginInvoke("Register", _args, callback, asyncState);
                return _result;
            }
            
            public string EndRegister(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("Register", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveExercise(Domain.CloudService.Users user, Domain.CloudService.Exercises exercise, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = user;
                _args[1] = exercise;
                System.IAsyncResult _result = base.BeginInvoke("SaveExercise", _args, callback, asyncState);
                return _result;
            }
            
            public string EndSaveExercise(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("SaveExercise", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetExercisesLight(Domain.CloudService.Users user, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = user;
                System.IAsyncResult _result = base.BeginInvoke("GetExercisesLight", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Domain.CloudService.Exercises> EndGetExercisesLight(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Domain.CloudService.Exercises> _result = ((System.Collections.ObjectModel.ObservableCollection<Domain.CloudService.Exercises>)(base.EndInvoke("GetExercisesLight", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetFullExercise(Domain.CloudService.Users user, int exerciseID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = user;
                _args[1] = exerciseID;
                System.IAsyncResult _result = base.BeginInvoke("GetFullExercise", _args, callback, asyncState);
                return _result;
            }
            
            public Domain.CloudService.Exercises EndGetFullExercise(System.IAsyncResult result) {
                object[] _args = new object[0];
                Domain.CloudService.Exercises _result = ((Domain.CloudService.Exercises)(base.EndInvoke("GetFullExercise", _args, result)));
                return _result;
            }
        }
    }
}
